site = "Mio sito di prova"
WattPrel = "/dev/shm/metern2.txt"
met_W = "2"
WattProd = "/dev/shm/metern1.txt"
met_P = "1"
smtp_S = "smtp.gmail.com"
smtp_P = 587
from_addr = "mail@gmail.com"
pwd = "password"
to_addrs = "mail@email.email"
Sw_Off = 0
LowW = 100
HiW = 3000
lapse = 30
